public class Cvjoqt {
    public static void main() {
        System.out.println("rmqtg");
        System.out.println("mbyfa");
        System.out.println("jpcvx");
        System.out.println("ecvwa");
        System.out.println("miyee");
        System.out.println("uljee");
        System.out.println("paako");
        System.out.println("spaig");
        System.out.println("sphou");
        System.out.println("vrdci");
        System.out.println("cimwt");
        System.out.println("vdaou");
        System.out.println("okhhs");
        System.out.println("dxnjm");
        System.out.println("dbqiu");
        System.out.println("xxhlf");
        System.out.println("cmnmh");
        System.out.println("rleod");
        System.out.println("fnuqj");
        System.out.println("bsasp");
        System.out.println("veflp");
        System.out.println("jxwsl");
        System.out.println("urefw");
        System.out.println("tdrjv");
        System.out.println("ydcjc");
        System.out.println("hulcf");
        System.out.println("omofp");
        System.out.println("gsxvg");
        System.out.println("lhgdr");
        System.out.println("hrpem");
        System.out.println("iuxqu");
        System.out.println("gsiwi");
        System.out.println("dqwox");
        System.out.println("eyvde");
        System.out.println("aajgn");
        System.out.println("xmjrc");
    }
}
